### ISSUE TITLE
Missing Milestones

### ISSUE THREAD

**Issue by mapfap** [SSD2015/TeamJDED#4]
- Please move the contents from this [page](https://github.com/SSD2015/TeamJDED/wiki/Iteration-Plan-EL1) to a file 'Iteration Plan EL1.md' and put it to your repo.
- Don't forget to complete milestone section and also create [GitHub's Milestones](https://github.com/SSD2015/TeamJDED/milestones) corresponding to it.

**Comment by waranyu1993** [comment]
done, thank you.

**Comment by waranyu1993** [comment]
Milestone coming soon
